import numpy as np
#arr = np.arange(14).reshape(2, 7)
#arr = np.arange(15)
#arr = np.zeros([3,4,6])
arr = np.random.random((2, 2, 3))
#arr = np.random.rand(2, 2, 3)
#arr = np.random.rand(2, 2, 3)
#arr = np.ones((2,3,4), dtype=np.int32)
#arr = np.random.randint(0, 2, 10)
print(arr)
